name: Deploy boxel-host
description: Deploy boxel-host to S3 and Cloudfront

inputs:
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$INPUT_ENVIRONMENT" = "production" ]; then
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-production" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E2DDEHLJXF5LQ8" >> $GITHUB_ENV
          echo "OWN_REALM_URL=https://realms.cardstack.com/demo/" >> $GITHUB_ENV
          echo "RESOLVED_BASE_REALM_URL=https://realms.cardstack.com/base/" >> $GITHUB_ENV
          echo "MATRIX_URL=https://matrix.cardstack.com" >> $GITHUB_ENV
        elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-staging" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E35TXLK9HIMESQ" >> $GITHUB_ENV
          echo "OWN_REALM_URL=https://realms-staging.stack.cards/demo/" >> $GITHUB_ENV
          echo "RESOLVED_BASE_REALM_URL=https://realms-staging.stack.cards/base/" >> $GITHUB_ENV
          echo "MATRIX_URL=https://matrix-staging.stack.cards" >> $GITHUB_ENV
        else
          echo "unrecognized environment"
          exit 1;
        fi

    - uses: volta-cli/action@v4
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Deploy
      shell: bash
      run: pnpm deploy:boxel-host ${{ inputs.environment }} --verbose

    - name: Send notification to Discord
      if: ${{ always() }}
      uses: cardstack/cardstack/.github/actions/discord-notification-deploy@main
      with:
        app: boxel-host
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
