name: Deploy boxel-host
description: Deploy boxel-host to S3 and Cloudfront

inputs:
  environment:
    description: Deployment environment
    required: true
  discord_webhook:
    description: Discord webhook URL
    required: true

# FIXME should these be passed in?
env:
  PNPM_VERSION: 7.2.1

  # This controls what version of node first boots pnpm, but pnpm itself will
  # read the .npmrc file and download a different version if they don't match.
  NODE_VERSION: 18.6.0

runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [ "$INPUT_ENVIRONMENT" = "production" ]; then
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-production" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E2DDEHLJXF5LQ8" >> $GITHUB_ENV
        elif [ "$INPUT_ENVIRONMENT" = "staging" ]; then
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/boxel-host" >> $GITHUB_ENV
          echo "AWS_S3_BUCKET=cardstack-boxel-host-staging" >> $GITHUB_ENV
          echo "AWS_CLOUDFRONT_DISTRIBUTION=E35TXLK9HIMESQ" >> $GITHUB_ENV
        else
          echo "unrecognized environment"
          exit 1;
        fi

    - uses: pnpm/action-setup@v2
      with:
        version: ${{ env.PNPM_VERSION }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: pnpm
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::680542703984:role/boxel-host
        aws-region: us-east-1

    - name: Deploy
      shell: bash
      run: pnpm deploy:boxel-host ${{ inputs.environment }} --verbose

    - name: Send notification to Discord
      if: ${{ always() }}
      uses: ./.github/actions/discord-notification-deploy
      with:
        app: boxel-host
        status: ${{ github.action_status }}
        environment: ${{ inputs.environment }}
        webhook: ${{ inputs.discord_webhook }}
