name: Init
description: Setup common dependencies

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "VOLTA_FEATURE_PNPM=1" >> $GITHUB_ENV

    - name: Cache volta tools
      id: cache-volta
      uses: actions/cache@v3
      env:
        cache-name: cache-volta-tools
      with:
        path: /opt/hostedtoolcache/volta/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

    - if: ${{ steps.cache-volta.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        echo "Cache miss!"

    - if: ${{ steps.cache-volta.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        echo "Hooray, the cache worked! New test!"

    - name: Run volta setup
      uses: volta-cli/action@v4

    - shell: bash
      run: |
        volta which node
        echo `volta which node`

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path -s)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      id: cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Prune pnpm store
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: pnpm store prune
