name: Init
description: Setup common dependencies

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "VOLTA_FEATURE_PNPM=1" >> $GITHUB_ENV

    - uses: volta-cli/action@v4

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path -s)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      id: cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Prune pnpm store
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: pnpm store prune
