name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  checks: write
  contents: read
  id-token: write
  pull-requests: write

jobs:
  host-test:
    strategy:
      matrix:
        one: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        two: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    name: Host Tests
    runs-on: ubuntu-latest
    concurrency:
      group: boxel-host-test-${{ github.head_ref || github.run_id }}-${{matrix.one}}-${{matrix.two}}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - run: echo ${{matrix.one}} ${{matrix.two}}
      - name: Build boxel-ui
        run: pnpm build
        working-directory: packages/boxel-ui/addon
      - name: Build host dist/ for fastboot
        run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: packages/host
      - name: Start realm servers
        run: pnpm start:all &
        working-directory: packages/realm-server
      - name: host test suite
        # FIXME restore
        run: pnpm test
        working-directory: packages/host
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: always()
        with:
          junit_files: junit/host.xml
          comment_mode: off
