name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  checks: write
  contents: read
  id-token: write
  pull-requests: write

jobs:
  host-test:
    strategy:
      matrix:
        one: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        two: [1, 2, 3, 4, 5]

    name: Host Tests
    runs-on: ubuntu-latest
    concurrency:
      group: boxel-host-test-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init
      - run: echo ${{matrix.one}} ${{matrix.two}}
      - name: Build boxel-ui
        run: pnpm build
        working-directory: packages/boxel-ui/addon
      - name: Build host dist/ for fastboot
        run: pnpm build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        working-directory: packages/host
      - name: Start realm servers
        run: pnpm start:all &
        working-directory: packages/realm-server
      - name: host test suite
        # FIXME restore
        run: pnpm test
        working-directory: packages/host
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2.9.0
        if: always()
        with:
          junit_files: junit/host.xml

  change-check:
    name: Check which packages changed
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      boxel: ${{ steps.filter.outputs.boxel }}
      ai-bot: ${{ steps.filter.outputs.ai-bot }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            boxel:
              - '.github/workflows/build-host.yml'
              - '.github/workflows/deploy-host.yml'
              - '.github/workflows/waypoint-build.yml'
              - '.github/workflows/waypoint-deploy.yml'
              - '.github/workflows/ci.yaml'
              - 'packages/base/**'
              - 'packages/boxel-ui/**'
              - 'packages/host/**'
              - 'packages/realm-server/**'
              - 'packages/runtime-common/**'
              - 'pnpm-lock.yaml'
            ai-bot:
              - '.github/workflows/waypoint-build.yml'
              - '.github/workflows/waypoint-deploy.yml'
              - '.github/workflows/ci.yaml'
              - 'packages/runtime-common/**'
              - 'packages/ai-bot/**'
              - 'pnpm-lock.yaml'
