name: Manual Deploy [realm-server]

on:
  # FIXME pull_request is for development only, should be a workflow_dispatch
  pull_request:
    paths:
      - "waypoint.hcl"

env:
  # FIXME this would be in the dispatch event
  ENVIRONMENT: staging

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [realm-base, realm-demo]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy ${{ matrix.app }}
        uses: ./.github/actions/deploy-realm-server
        with:
          app_name: ${{ matrix.app }}
          environment: ${{ env.ENVIRONMENT }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          production_waypoint_server_token: ${{ secrets.PRODUCTION_WAYPOINT_SERVER_TOKEN }}
          production_waypoint_server_address: ${{ secrets.PRODUCTION_WAYPOINT_SERVER_ADDR }}
          staging_waypoint_server_token: ${{ secrets.STAGING_WAYPOINT_SERVER_TOKEN }}
          staging_waypoint_server_address: ${{ secrets.STAGING_WAYPOINT_SERVER_ADDR }}

