name: Manual Deploy [boxel]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

env:
  ENVIRONMENT: ${{ inputs.environment }}
  VOLTA_FEATURE_PNPM: 1

permissions:
  contents: read
  id-token: write

jobs:
  deploy-host:
    name: Deploy host
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy boxel-host if changes have happened
        uses: ./.github/actions/deploy-boxel-host
        with:
          environment: ${{ inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

  build-realm-server:
    name: Build realm-server
    uses: ./.github/workflows/waypoint-build.yml
    secrets: inherit
    with:
      app: "realm-demo"
      environment: "staging"

  deploy-realm-server:
    name: Deploy realm server to staging
    needs: [build-realm-server]
    uses: ./.github/workflows/waypoint-deploy.yml
    secrets: inherit
    with:
      app: "realm-demo"
      environment: "staging"
