name: Manual Deploy [realm-server]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

env:
  # FIXME this would be in the dispatch event
  ENVIRONMENT: staging
  VOLTA_FEATURE_PNPM: 1

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # We are not currently using the realm-base server. Rather the base realm
        # and demo realm are both being hosted by the realms server
        # app: [realm-base, realm-demo]
        app: [realm-demo]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy ${{ matrix.app }}
        uses: ./.github/actions/deploy-realm-server
        with:
          app_name: ${{ matrix.app }}
          environment: ${{ inputs.environment }}
          discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
          production_waypoint_server_token: ${{ secrets.PRODUCTION_WAYPOINT_SERVER_TOKEN }}
          production_waypoint_server_address: ${{ secrets.PRODUCTION_WAYPOINT_SERVER_ADDR }}
          staging_waypoint_server_token: ${{ secrets.STAGING_WAYPOINT_SERVER_TOKEN }}
          staging_waypoint_server_address: ${{ secrets.STAGING_WAYPOINT_SERVER_ADDR }}
