name: Manual Deploy [boxel]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  build-host:
    name: Build host
    uses: ./.github/workflows/build-host.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}

  build-realm-server:
    name: Build realm-server
    uses: cardstack/gh-actions/.github/workflows/waypoint-build.yml@main
    secrets: inherit
    with:
      app: "realm-demo"
      environment: ${{ inputs.environment }}
      restore-mtime: true

  deploy-host:
    name: Deploy host
    needs: [build-host, build-realm-server]
    uses: ./.github/workflows/deploy-host.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}

  deploy-realm-server:
    name: Deploy realm server to staging
    needs: [build-host, build-realm-server]
    uses: cardstack/gh-actions/.github/workflows/waypoint-deploy.yml@fix/wait-service-stable-directory
    secrets: inherit
    with:
      app: "realm-demo"
      environment: ${{ inputs.environment }}
