name: Manual Deploy [vscode-boxel-tools]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  # FIXME remove
  pull_request:

jobs:
  check-version:
    name: Check for changes since last version update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for version change and subsequent modifications
        id: check
        run: |
          PACKAGE_JSON="packages/vscode-boxel-tools/package.json"
          LAST_VERSION_CHANGE=$(git log -1 --pretty=format:%H --grep="version" -- $PACKAGE_JSON)
          echo "Last version change commit: $LAST_VERSION_CHANGE"

          if [ -z "$LAST_VERSION_CHANGE" ]; then
            echo "Error: No version change found in git history. Will not publish."
            exit 1
          else
            echo "Checking for changes since version was updated in $LAST_VERSION_CHANGE"
            CHANGES=$(git diff --name-only $LAST_VERSION_CHANGE HEAD -- packages/vscode-boxel-tools packages/runtime-common)
            echo "Changes detected:"
            echo "$CHANGES"

            if [ -z "$CHANGES" ]; then
              echo ""
              echo "No changes detected since last version update. Proceeding with publish."
              exit 0
            else
              echo ""
              echo "Error: Changes have been detected since the extension version was updated. Will not publish."
              exit 1
            fi
          fi

  publish:
    name: Package, test, and publish VS Code Boxel Tools extension
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Build boxel-ui
        run: pnpm build
        working-directory: packages/boxel-ui/addon
      - name: Package
        run: pnpm vscode:package
        working-directory: packages/vscode-boxel-tools
      - name: Test
        run: xvfb-run -a pnpm test
        working-directory: packages/vscode-boxel-tools
      - name: Publish
        run: pnpm vscode:publish
        working-directory: packages/vscode-boxel-tools
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
