name: Manual Deploy [boxel]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  build-host:
    name: Build host
    uses: ./.github/workflows/build-host.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}

  build-realm-server:
    name: Build realm-server
    uses: cardstack/gh-actions/.github/workflows/waypoint-build.yml@main
    secrets: inherit
    with:
      app: "boxel-realm-server"
      environment: ${{ inputs.environment }}
      restore-mtime: true
      working-directory: "packages/realm-server"

  deploy-host:
    name: Deploy host
    needs: [build-host, build-realm-server]
    uses: ./.github/workflows/deploy-host.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}

  realm-server-efs-config:
    name: EFS Config
    needs: [build-realm-server]
    uses: ./.github/workflows/realm-server-efs-config.yml
    with:
      environment: ${{ inputs.environment }}

  deploy-realm-server:
    name: Deploy realm server
    needs:
      - build-host
      - realm-server-efs-config
    uses: cardstack/gh-actions/.github/workflows/waypoint-deploy.yml@main
    secrets: inherit
    with:
      app: "boxel-realm-server"
      environment: ${{ inputs.environment }}
      working-directory: "packages/realm-server"
      efs-config: ${{ needs.realm-server-efs-config.outputs.config }}
      retain: "0"
