name: Manual Deploy [vscode-boxel-tools]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  # FIXME remove
  pull_request:

jobs:
  check-version:
    name: Check for changes since last version update
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.check.outputs.should_publish }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for version change and subsequent modifications
        id: check
        run: |
          PACKAGE_JSON="packages/vscode-boxel-tools/package.json"
          LAST_VERSION_CHANGE=$(git log -1 --pretty=format:%H --grep="version" -- $PACKAGE_JSON)
          echo "Last version change commit: $LAST_VERSION_CHANGE"

          if [ -z "$LAST_VERSION_CHANGE" ]; then
            echo "No version change found in git history. Proceeding with publish."
            echo "should_publish=true" >> $GITHUB_OUTPUT
          else
            echo "Checking for changes since $LAST_VERSION_CHANGE"
            CHANGES=$(git diff --name-only $LAST_VERSION_CHANGE HEAD -- packages/vscode-boxel-tools packages/realm-server)
            echo "Changes detected:"
            echo "$CHANGES"

            if [ -z "$CHANGES" ]; then
              echo "No changes detected since last version update. Skipping publish."
              echo "should_publish=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected since last version update. Proceeding with publish."
              echo "should_publish=true" >> $GITHUB_OUTPUT
            fi
          fi

  publish:
    name: Package, test, and publish VS Code Boxel Tools extension
    needs: check-version
    if: needs.check-version.outputs.should_publish == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/init
      - name: Build boxel-ui
        run: pnpm build
        working-directory: packages/boxel-ui/addon
      - name: Package
        run: pnpm vscode:package
        working-directory: packages/vscode-boxel-tools
      - name: Test
        run: xvfb-run -a pnpm test
        working-directory: packages/vscode-boxel-tools
      - name: Publish
        if: success()
        run: pnpm vscode:publish
        working-directory: packages/vscode-boxel-tools
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
