name: Restart [realm-server]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up env
        shell: bash
        working-directory: "packages/realm-server"
        env:
          INPUT_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "WAYPOINT_SERVER_TLS=1" >> $GITHUB_ENV
          if [ "${{ inputs.environment }}" = "production" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::120317779495:role/waypoint" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_ADDR=${{ secrets.PRODUCTION_WAYPOINT_SERVER_ADDR }}" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_TOKEN=${{ secrets.PRODUCTION_WAYPOINT_SERVER_TOKEN }}" >> $GITHUB_ENV
            cp waypoint.prod.hcl waypoint.hcl
          elif [ "${{ inputs.environment }}" = "staging" ]; then
            echo "AWS_ROLE_ARN=arn:aws:iam::680542703984:role/waypoint" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_ADDR=${{ secrets.STAGING_WAYPOINT_SERVER_ADDR }}" >> $GITHUB_ENV
            echo "WAYPOINT_SERVER_TOKEN=${{ secrets.STAGING_WAYPOINT_SERVER_TOKEN }}" >> $GITHUB_ENV
          else
            echo "unrecognized environment"
            exit 1;
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - uses: lucasmelin/setup-waypoint@v1
        with:
          version: "0.11.3"

      - name: Restart realm-server
        uses: cardstack/gh-actions/waypoint-ecs-restart@main
        with:
          app: "boxel-realm-server"

      - name: Wait service stable
        uses: cardstack/gh-actions/waypoint-wait-service-stable@main
        with:
          app: "boxel-realm-server"
          waypoint-hcl: packages/realm-server/waypoint.hcl
