name: Restart [realm-server]

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: false
        default: staging

permissions:
  contents: read
  id-token: write

jobs:
  restart:
    uses: cardstack/gh-actions/.github/workflows/ecs-force-new-deployment.yml@main
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      cluster: ${{ inputs.environment }}
      service-name: "boxel-realm-server-${{ inputs.environment }}"
