name: YAML Lint

on:
  pull_request:
    paths:
      - "**.yml"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: ibiqlik/action-yamllint@v3.1
        with:
          config_file: ".github/.yamllint.yml"
          file_or_dir: ".github"
          strict: true
